# Generated by Django 5.1 on 2024-08-13 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passowrd',
            new_name='password',
        ),
    ]
