# Generated by Django 5.1 on 2024-08-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task_manager', '0002_rename_passowrd_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(max_length=1000, unique=True),
        ),
    ]
