# Generated by Django 5.1 on 2024-08-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task_manager', '0003_alter_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
