# Generated by Django 5.1 on 2024-08-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task_manager', '0005_user_bio_user_img_url_user_job_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
