# Generated by Django 5.1 on 2024-08-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task_manager', '0006_alter_user_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img_url',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
