# Generated by Django 5.1 on 2024-08-13 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task_manager', '0007_alter_user_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='job_Role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
