# Generated by Django 5.1 on 2024-08-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task_manager', '0008_remove_user_job_role_remove_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img_url',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
