# Generated by Django 5.1 on 2024-08-13 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task_manager', '0010_alter_user_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='img_url',
        ),
    ]
