# Generated by Django 5.2 on 2025-04-30 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_follow_user_follow_followed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='followed',
            new_name='follow_user',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='follower',
            new_name='following',
        ),
    ]
