# Generated by Django 5.2 on 2025-04-30 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_followed_follow_follow_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='follow_user',
            new_name='user',
        ),
    ]
