# Generated by Django 5.2 on 2025-05-01 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post_user',
        ),
    ]
