# Generated by Django 5.2 on 2025-05-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_message_is_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
